name: "Malem Alarm"
description: "Listener for Malem BLUE-T BLE bedwetting sensor"
version: "1.4.6"
slug: "malem_alarm"
init: false
arch:
  - aarch64
  - amd64
  - armv7

host_dbus: true

privileged:
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN

devices: []
uart: false
usb: false

map:
  - config:rw

options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic_prefix: "malem"
  dry_timeout: 15
  log_level: "info"
  sensor_mac: ""

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
  dry_timeout: int
  log_level: list(debug|info|warning|error)
  sensor_mac: str

url: "https://github.com/realliljennie-a11y/malem-ha-addon"
